### ISSUE TITLE
Is IMU sensor required?

### ISSUE THREAD

**Issue by ywiyogo** [nkuwenjian/laser_scan_matcher#4]
Hi @nkuwenjian , 

currently, I don't have IMU mounted on my robot. I can create the map, but is a little bit distorted. Does laser-scan-matcher need an IMU sensor? 
If yes, where can I find the code segment of the IMU sensor fusion?

**Comment by nkuwenjian** [comment]
Hi @ywiyogo ,

Both IMU and odometry can provide a good initial guess for the laser scan matching algorithm. Unfortunately, this project does not currently have an interface to integrate IMU data. 

If you want to build an accurate map without IMU, the state-of-the-art Google Cartographer is recommended.

**Comment by ywiyogo** [comment]
Ok, thanks for the hint.
